name: Type Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ts-type-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Set up Node with cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Type check code via TypeScript
        run: npm run ts
